# -*- coding: utf-8 -*-
"""Sigmoid.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mT8Z9tuiRltaWIsBL1LSzk8E4E_UAAMt
"""

import numpy as np
import matplotlib.pyplot as plt

x = np.linspace(-10, 10, 400)
y = 1 / (1 + np.exp(-x))

plt.figure()
plt.plot(x, y)
plt.xlabel("Input")
plt.ylabel("Output")
plt.title("Sigmoid Activation Function")
plt.show()