# -*- coding: utf-8 -*-
"""Sigmoid.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mT8Z9tuiRltaWIsBL1LSzk8E4E_UAAMt
"""

import numpy as np
import matplotlib.pyplot as plt
import streamlit as st

x = np.linspace(-10, 10, 400)
y = 1 / (1 + np.exp(-x))

fig, ax = plt.subplots() # 2. Using subplots is the best practice for Streamlit
ax.plot(x, y)
ax.set_xlabel("Input")
ax.set_ylabel("Output")
ax.set_title("Sigmoid Activation Function")

st.pyplot(fig) # 3. Changed from plt.show()